name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get metadata for Docker minimal image
        id: metadata_minimal
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            minimal
      - name: Get metadata for Docker latest image
        id: metadata_latest
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
      - name: Build and push minimal image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.Minimal
          tags: ${{ steps.metadata_minimal.outputs.tags }}
          labels: ${{ steps.metadata_minimal.outputs.labels }}
          push: true
      - name: Build and push latest image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.metadata_latest.outputs.tags }}
          labels: ${{ steps.metadata_latest.outputs.labels }}
          push: true
